server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: interaction-service

  datasource:
    url: jdbc:postgresql://postgres:5432/interaction_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL_MINUTES:10}m
redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}
cache:
  ttl:
    minutes: ${CACHE_TTL_MINUTES:10}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    enable:
      # базовые HTTP-метрики
      http.server.requests: true
      # метрики JVM
      jvm.memory.used: true
      jvm.gc.max.data.size: true
      # кэш
      cache.gets: true
      cache.puts: true
      cache.evictions: true

logging:
  level:
    ru.vladuss.informantservice: DEBUG

